name: taller1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.2+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.1
  url_launcher: ^6.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/si.jpeg
    - assets/images/cina.jpg
